steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'install']
options:
  logging: 'CLOUD_LOGGING_ONLY'
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _PROJECT_ID: '	http-terraform-storage-lb'
  _ZONE: 'us-central1-f'
  build:
    service_account: http-load-balancer@http-terraform-storage-lb.iam.gserviceaccount.com
    logs_bucket: gs://my-bucket-tffzzz/
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/http-terraform-storage-lb/my-java-app'
      - '.'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-java-app'
      - '--image'
      - 'gcr.io/http-terraform-storage-lb/my-java-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
