steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-java-app'
      - '.'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-java-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/my-java-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
