steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'install']
options:
  logging: 'CLOUD_LOGGING_ONLY'
  build:
    service_account: my-service-account@my-project.iam.gserviceaccount.com
    logs_bucket: my-logs-bucket
steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/http-terraform-storage-lb/my-java-app'
      - '.'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-java-app'
      - '--image'
      - 'gcr.io/http-terraform-storage-lb/my-java-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
