name: CI/CD Pipeline for Apache HTTP Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Apache HTTP Server
      run: |
        sudo apt-get update
        sudo apt-get install apache2 -y

    - name: Copy website files
      run: |
        sudo cp -r ./website/* /var/www/html/

    - name: Start Apache HTTP Server
      run: |
        sudo systemctl start apache2.service

    - name: Test website
      run: |
        curl http://localhost/

    - name: Stop Apache HTTP Server
      run: |
        sudo systemctl stop apache2.service
