name: CI/CD Pipeline for Apache HTTP Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: http-terraform-storage-lb
        service_account_email: http-load-balancer@http-terraform-storage-lb.iam.gserviceaccount.com
        service_account_key: 2538c4604c577452ed6fa2a4c12b224a42253ff9
    - name: Start GCP instance
      run: |
        gcloud compute instances start instance-terraform --zone us-west1-b
        gcloud compute ssh instance-terraform --zone us-west1-b --command "cd /home/ragavel1262000/"
      env:
        GOOGLE_APPLICATION_CREDENTIALS: 2538c4604c577452ed6fa2a4c12b224a42253ff9

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Apache HTTP Server
      run: |
        sudo apt-get update
        sudo apt-get install apache2 -y
        sudo apt-get install curl -y

    - name: Copy file to webserver
      run: |
        sudo cp /home/ragavel1262000/first /var/www/html/


    - name: Start Apache HTTP Server
      run: |
        sudo systemctl start apache2.service

    - name: Test website
      run: |
        curl http://34.145.105.152/

    - name: Stop Apache HTTP Server
      run: |
        sudo systemctl stop apache2.service
