name: CI/CD Pipeline for Apache HTTP Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Apache HTTP Server
      run: |
        sudo apt-get update
        sudo apt-get install apache2 -y
        sudo apt-get install curl -y

    - name: Copy file to webserver
      run: |
        sudo scp \Downloads\Diagram Document - Terraform_gcp ragavel1262000@34.145.105.152:/var/www/html/


    - name: Start Apache HTTP Server
      run: |
        sudo systemctl start apache2.service

    - name: Test website
      run: |
        curl http://34.145.105.152/

    - name: Stop Apache HTTP Server
      run: |
        sudo systemctl stop apache2.service
