name: CI/CD Pipeline for Apache HTTP Server

on:
  push:
    branches:
      - main

  jobs:
    build:
      runs-on: self-hosted
      executor:
        name: remote-debian
        runs-on: ubuntu-latest
        remote-user: debian
        ssh-key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBArm/oncI6dk6fDY6iaUXQNVSWtbQsxZpLQFmlIxPO5SWMtnbt/TmYaJa6Hh9uoA10Up43HIYLdkgpKUthXzrDI= google-ssh {"userName":"ragavel1262000@gmail.com","expireOn":"2023-04-03T06:09:48+0000"}
      env:
        REMOTE_HOST: 10.138.0.2

    - name: Install Apache HTTP Server
      run: |
        sudo apt-get update
        sudo apt-get install apache2 -y
        sudo apt-get install curl -y

    - name: Copy file to webserver
      run: |
        sudo cp /home/ragavel1262000/first /var/www/html/


    - name: Start Apache HTTP Server
      run: |
        sudo systemctl start apache2.service

    - name: Test website
      run: |
        curl http://34.145.105.152/

    - name: Stop Apache HTTP Server
      run: |
        sudo systemctl stop apache2.service
